In [1]:
import pandas as pd
import numpy as np

In [2]:
# Men Data
men_test = pd.read_csv('../Web_Scraping/Scraped_Data/Men_Test_Analysis.csv')

In [3]:
men_test.shape

(193, 12)

In [4]:
men_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           193 non-null    int64
 1   Player         193 non-null    object
 2   Matches        193 non-null    int64
 3   Innings        193 non-null    int64
 4   Average        193 non-null    float64
 5   Strike Rate    193 non-null    object
 6   Highest Score  193 non-null    object
 7   Fours          193 non-null    object
 8   Sixes          193 non-null    object
 9   Fifties        193 non-null    object
 10  Hundreds       193 non-null    object
 11  Runs           193 non-null    int64
dtypes: float64(1), int64(4), object(7)
memory usage: 18.2+ KB

In [5]:
men_test.isnull().sum()

Rank             0
Player           0
Matches          0
Innings          0
Average          0
Strike Rate      0
Highest Score    0
Fours            0
Sixes            0
Fifties          0
Hundreds         0
Runs             0
dtype: int64

In [6]:
men_test.dtypes

Rank               int64
Player            object
Matches            int64
Innings            int64
Average          float64
Strike Rate       object
Highest Score     object
Fours             object
Sixes             object
Fifties           object
Hundreds          object
Runs               int64
dtype: object

In [7]:
men_test.head()

,Rank,Player,Matches,Innings,Average,Strike Rate,Highest Score,Fours,Sixes,Fifties,Hundreds,Runs
0,1,Sachin Tendulkar,200,329,53.78,54.09,248,2058,69,68,51,15921
1,2,Rahul Dravid,164,286,52.31,42.51,270,1655,21,63,36,13288
2,3,Sunil Gavaskar,125,214,51.12,66.04,236,1016,26,45,34,10122
3,4,Virat Kohli,123,210,46.85,55.57,254,1027,30,31,30,9230
4,5,VVS Laxman,134,225,45.97,49.37,281,1135,5,56,17,8781

In [8]:
men_test.columns = (
    men_test.columns
    .str.replace(" ", "_")
    .str.strip()
)

In [9]:
men_test = men_test.rename(
    columns = {
        "Rank": "Test_Rank",
        "Matches": "Test_Matches",
        "Innings": "Test_Innings",
        "Average": "Test_Average",
        "Strike_Rate": "Test_Strike_Rate",
        "Highest_Score": "Test_Highest_Score",
        "Fours": "Test_Fours",
        "Sixes": "Test_Sixes",
        "Fifties": "Test_Fifties",
        "Hundreds": "Test_Hundreds",
        "Runs": "Test_Runs",
        
})

In [10]:
men_test.head(10)

,Test_Rank,Player,Test_Matches,Test_Innings,Test_Average,Test_Strike_Rate,Test_Highest_Score,Test_Fours,Test_Sixes,Test_Fifties,Test_Hundreds,Test_Runs
0,1,Sachin Tendulkar,200,329,53.78,54.09,248,2058,69,68,51,15921
1,2,Rahul Dravid,164,286,52.31,42.51,270,1655,21,63,36,13288
2,3,Sunil Gavaskar,125,214,51.12,66.04,236,1016,26,45,34,10122
3,4,Virat Kohli,123,210,46.85,55.57,254,1027,30,31,30,9230
4,5,VVS Laxman,134,225,45.97,49.37,281,1135,5,56,17,8781
5,6,Virender Sehwag,104,180,49.34,82.23,319,1233,91,32,23,8586
6,7,Sourav Ganguly,113,188,42.17,51.25,239,900,57,35,16,7212
7,8,Cheteshwar Pujara,103,176,43.60,44.36,206,863,16,35,19,7195
8,9,Dilip Vengsarkar,116,185,41.37,59.98,166,560,17,35,17,6868
9,10,Mohammad Azharuddin,99,147,45.03,63.08,199,720,19,21,22,6215

In [11]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Men_Test"
men_test.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Men_Test' in database 'Indian_Cricket_Analysis'.

In [12]:
men_test.to_csv('Cleaned_CSV/Clean_Men_Test.csv', index = False, encoding = 'utf-8')