In [1]:
import pandas as pd
import numpy as np

In [2]:
# Men Data
men_t20i = pd.read_csv('../Web_Scraping/Scraped_Data/Men_T20i_Analysis.csv')

In [3]:
men_t20i.shape

(96, 12)

In [4]:
men_t20i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           96 non-null     int64
 1   Player         96 non-null     object
 2   Matches        96 non-null     int64
 3   Innings        96 non-null     int64
 4   Average        96 non-null     float64
 5   Strike Rate    96 non-null     float64
 6   Highest Score  96 non-null     int64
 7   Fours          96 non-null     object
 8   Sixes          96 non-null     object
 9   Fifties        96 non-null     object
 10  Hundreds       96 non-null     object
 11  Runs           96 non-null     int64
dtypes: float64(2), int64(5), object(5)
memory usage: 9.1+ KB

In [5]:
men_t20i.isnull().sum()

Rank             0
Player           0
Matches          0
Innings          0
Average          0
Strike Rate      0
Highest Score    0
Fours            0
Sixes            0
Fifties          0
Hundreds         0
Runs             0
dtype: int64

In [6]:
men_t20i.dtypes

Rank               int64
Player            object
Matches            int64
Innings            int64
Average          float64
Strike Rate      float64
Highest Score      int64
Fours             object
Sixes             object
Fifties           object
Hundreds          object
Runs               int64
dtype: object

In [7]:
men_t20i.head()

,Rank,Player,Matches,Innings,Average,Strike Rate,Highest Score,Fours,Sixes,Fifties,Hundreds,Runs
0,1,Rohit Sharma,159,151,32.05,140.89,121,383,205,32,5,4231
1,2,Virat Kohli,125,117,48.69,137.04,122,369,124,38,1,4188
2,3,Surya Kumar Yadav,113,107,36.35,162.94,117,297,179,25,4,3272
3,4,Hardik Pandya,138,109,28.24,145.91,71,168,126,9,-,2288
4,5,KL Rahul,72,68,37.75,139.12,110,191,99,22,2,2265

In [8]:
men_t20i.columns = (
    men_t20i.columns
    .str.replace(" ", "_")
    .str.strip()
)

In [9]:
men_t20i = men_t20i.rename(
    columns = {
        "Rank": "T20I_Rank",
        "Matches": "T20I_Matches",
        "Innings": "T20I_Innings",
        "Average": "T20I_Average",
        "Strike_Rate": "T20I_Strike_Rate",
        "Highest_Score": "T20I_Highest_Score",
        "Fours": "T20I_Fours",
        "Sixes": "T20I_Sixes",
        "Fifties": "T20I_Fifties",
        "Hundreds": "T20I_Hundreds",
        "Runs": "T20I_Runs",
        
})

In [10]:
men_t20i.head(10)

,T20I_Rank,Player,T20I_Matches,T20I_Innings,T20I_Average,T20I_Strike_Rate,T20I_Highest_Score,T20I_Fours,T20I_Sixes,T20I_Fifties,T20I_Hundreds,T20I_Runs
0,1,Rohit Sharma,159,151,32.05,140.89,121,383,205,32,5,4231
1,2,Virat Kohli,125,117,48.69,137.04,122,369,124,38,1,4188
2,3,Surya Kumar Yadav,113,107,36.35,162.94,117,297,179,25,4,3272
3,4,Hardik Pandya,138,109,28.24,145.91,71,168,126,9,-,2288
4,5,KL Rahul,72,68,37.75,139.12,110,191,99,22,2,2265
5,6,Shikhar Dhawan,68,66,27.92,126.36,92,191,50,11,-,1759
6,7,MS Dhoni,98,85,37.60,126.13,56,116,52,2,-,1617
7,8,Suresh Raina,78,66,29.18,134.87,101,145,58,5,1,1605
8,9,Abhishek Sharma,50,49,33.80,192.83,135,160,103,11,2,1589
9,10,N. Tilak Varma,53,50,44.14,143.49,120,117,75,7,2,1501

In [11]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Men_T20i"
men_t20i.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Men_T20i' in database 'Indian_Cricket_Analysis'.

In [12]:
men_t20i.to_csv('Cleaned_CSV/Clean_Men_T20i.csv', index = False, encoding = 'utf-8')