In [1]:
import pandas as pd
import numpy as np

In [2]:
# Men Data
men_odi = pd.read_csv('../Web_Scraping/Scraped_Data/Men_Odi_Analysis.csv')

In [3]:
men_odi.shape

(239, 12)

In [4]:
men_odi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           239 non-null    int64
 1   Player         239 non-null    object
 2   Matches        239 non-null    int64
 3   Innings        239 non-null    int64
 4   Average        239 non-null    float64
 5   Strike Rate    239 non-null    float64
 6   Highest Score  239 non-null    int64
 7   Fours          239 non-null    object
 8   Sixes          239 non-null    object
 9   Fifties        239 non-null    object
 10  Hundreds       239 non-null    object
 11  Runs           239 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 22.5+ KB

In [5]:
men_odi.isnull().sum()

Rank             0
Player           0
Matches          0
Innings          0
Average          0
Strike Rate      0
Highest Score    0
Fours            0
Sixes            0
Fifties          0
Hundreds         0
Runs             0
dtype: int64

In [6]:
men_odi.dtypes

Rank               int64
Player            object
Matches            int64
Innings            int64
Average          float64
Strike Rate      float64
Highest Score      int64
Fours             object
Sixes             object
Fifties           object
Hundreds          object
Runs               int64
dtype: object

In [7]:
men_odi.head()

,Rank,Player,Matches,Innings,Average,Strike Rate,Highest Score,Fours,Sixes,Fifties,Hundreds,Runs
0,1,Sachin Tendulkar,463,452,44.83,86.23,200,2016,195,96,49,18426
1,2,Virat Kohli,311,299,58.71,93.82,183,1376,168,77,54,14797
2,3,Rohit Sharma,285,277,48.83,92.97,264,1107,363,62,33,11720
3,4,Sourav Ganguly,311,300,41.02,73.70,183,1122,190,72,22,11363
4,5,Rahul Dravid,344,318,39.16,71.23,153,950,42,83,12,10889

In [8]:
men_odi.columns = (
    men_odi.columns
    .str.replace(" ", "_")
    .str.strip()
)

In [9]:
men_odi = men_odi.rename(
    columns = {
        "Rank": "ODI_Rank",
        "Matches": "ODI_Matches",
        "Innings": "ODI_Innings",
        "Average": "ODI_Average",
        "Strike_Rate": "ODI_Strike_Rate",
        "Highest_Score": "ODI_Highest_Score",
        "Fours": "ODI_Fours",
        "Sixes": "ODI_Sixes",
        "Fifties": "ODI_Fifties",
        "Hundreds": "ODI_Hundreds",
        "Runs": "ODI_Runs",
        
})

In [10]:
men_odi.head(10)

,ODI_Rank,Player,ODI_Matches,ODI_Innings,ODI_Average,ODI_Strike_Rate,ODI_Highest_Score,ODI_Fours,ODI_Sixes,ODI_Fifties,ODI_Hundreds,ODI_Runs
0,1,Sachin Tendulkar,463,452,44.83,86.23,200,2016,195,96,49,18426
1,2,Virat Kohli,311,299,58.71,93.82,183,1376,168,77,54,14797
2,3,Rohit Sharma,285,277,48.83,92.97,264,1107,363,62,33,11720
3,4,Sourav Ganguly,311,300,41.02,73.70,183,1122,190,72,22,11363
4,5,Rahul Dravid,344,318,39.16,71.23,153,950,42,83,12,10889
5,6,MS Dhoni,350,297,50.57,87.56,183,826,229,73,10,10773
6,7,Mohammad Azharuddin,334,308,36.92,74.02,153,622,77,58,7,9378
7,8,Yuvraj Singh,304,278,36.55,87.67,150,908,155,52,14,8701
8,9,Virender Sehwag,251,245,35.05,104.33,219,1132,136,38,15,8273
9,10,Shikhar Dhawan,167,164,44.11,91.35,143,842,79,39,17,6793

In [11]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Men_Odi"
men_odi.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Men_Odi' in database 'Indian_Cricket_Analysis'.

In [12]:
men_odi.to_csv('Cleaned_CSV/Clean_Men_Odi.csv', index = False, encoding = 'utf-8')