In [1]:
import pandas as pd
import numpy as np

In [2]:
# Women Data
women_odi = pd.read_csv('../Web_Scraping/Scraped_Data/Women_Odi_Analysis.csv')

In [3]:
women_odi.shape

(140, 12)

In [4]:
women_odi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           140 non-null    int64
 1   Player         140 non-null    object
 2   Matches        140 non-null    int64
 3   Innings        140 non-null    int64
 4   Average        140 non-null    float64
 5   Strike Rate    140 non-null    object
 6   Highest Score  140 non-null    int64
 7   Fours          140 non-null    object
 8   Sixes          140 non-null    object
 9   Fifties        140 non-null    object
 10  Hundreds       140 non-null    object
 11  Runs           140 non-null    int64
dtypes: float64(1), int64(5), object(6)
memory usage: 13.3+ KB

In [5]:
women_odi.isnull().sum()

Rank             0
Player           0
Matches          0
Innings          0
Average          0
Strike Rate      0
Highest Score    0
Fours            0
Sixes            0
Fifties          0
Hundreds         0
Runs             0
dtype: int64

In [6]:
women_odi.dtypes

Rank               int64
Player            object
Matches            int64
Innings            int64
Average          float64
Strike Rate       object
Highest Score      int64
Fours             object
Sixes             object
Fifties           object
Hundreds          object
Runs               int64
dtype: object

In [7]:
women_odi.head()

,Rank,Player,Matches,Innings,Average,Strike Rate,Highest Score,Fours,Sixes,Fifties,Hundreds,Runs
0,1,Mithali Raj,232,211,50.68,67.54,125,805,19,64,7,7805
1,2,Smriti Mandhana,120,120,47.88,90.36,136,653,74,35,14,5411
2,3,Harmanpreet Kaur,164,143,37.22,76.86,171,448,57,24,7,4541
3,4,Anjum Chopra,127,112,31.38,-,100,-,-,18,1,2856
4,5,Deepti Sharma,124,106,35.98,70.43,188,263,19,18,1,2771

In [8]:
women_odi.columns = (
    women_odi.columns
    .str.replace(" ", "_")
    .str.strip()
)

In [9]:
women_odi = women_odi.rename(
    columns = {
        "Rank": "ODI_Rank",
        "Matches": "ODI_Matches",
        "Innings": "ODI_Innings",
        "Average": "ODI_Average",
        "Strike_Rate": "ODI_Strike_Rate",
        "Highest_Score": "ODI_Highest_Score",
        "Fours": "ODI_Fours",
        "Sixes": "ODI_Sixes",
        "Fifties": "ODI_Fifties",
        "Hundreds": "ODI_Hundreds",
        "Runs": "ODI_Runs",
        
})

In [10]:
women_odi.head(10)

,ODI_Rank,Player,ODI_Matches,ODI_Innings,ODI_Average,ODI_Strike_Rate,ODI_Highest_Score,ODI_Fours,ODI_Sixes,ODI_Fifties,ODI_Hundreds,ODI_Runs
0,1,Mithali Raj,232,211,50.68,67.54,125,805,19,64,7,7805
1,2,Smriti Mandhana,120,120,47.88,90.36,136,653,74,35,14,5411
2,3,Harmanpreet Kaur,164,143,37.22,76.86,171,448,57,24,7,4541
3,4,Anjum Chopra,127,112,31.38,-,100,-,-,18,1,2856
4,5,Deepti Sharma,124,106,35.98,70.43,188,263,19,18,1,2771
5,6,Punam Raut,73,73,34.83,58.26,109,261,6,15,3,2299
6,7,Jaya Sharma,77,75,30.75,-,138,-,-,14,2,2091
7,8,Jemimah Rodrigues,62,59,34.15,90.31,127,198,5,8,3,1810
8,9,Anju Jain,65,65,29.81,-,90,-,-,12,-,1729
9,10,Jhulan Goswami,204,121,14.61,-,57,-,-,1,-,1228

In [11]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Women_Odi"
women_odi.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Women_Odi' in database 'Indian_Cricket_Analysis'.

In [12]:
women_odi.to_csv('Cleaned_CSV/Clean_Women_Odi.csv', index = False, encoding = 'utf-8')