In [1]:
import pandas as pd
import numpy as np

In [2]:
# Women Data
women_t20i = pd.read_csv('../Web_Scraping/Scraped_Data/Women_T20i_Analysis.csv')

In [3]:
women_t20i.shape

(82, 12)

In [4]:
women_t20i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           82 non-null     int64
 1   Player         82 non-null     object
 2   Matches        82 non-null     int64
 3   Innings        82 non-null     int64
 4   Average        82 non-null     float64
 5   Strike Rate    82 non-null     object
 6   Highest Score  82 non-null     int64
 7   Fours          82 non-null     object
 8   Sixes          82 non-null     object
 9   Fifties        82 non-null     object
 10  Hundreds       82 non-null     object
 11  Runs           82 non-null     int64
dtypes: float64(1), int64(5), object(6)
memory usage: 7.8+ KB

In [5]:
women_t20i.isnull().sum()

Rank             0
Player           0
Matches          0
Innings          0
Average          0
Strike Rate      0
Highest Score    0
Fours            0
Sixes            0
Fifties          0
Hundreds         0
Runs             0
dtype: int64

In [6]:
women_t20i.dtypes

Rank               int64
Player            object
Matches            int64
Innings            int64
Average          float64
Strike Rate       object
Highest Score      int64
Fours             object
Sixes             object
Fifties           object
Hundreds          object
Runs               int64
dtype: object

In [7]:
women_t20i.head()

,Rank,Player,Matches,Innings,Average,Strike Rate,Highest Score,Fours,Sixes,Fifties,Hundreds,Runs
0,1,Smriti Mandhana,171,165,30.25,125.18,112,614,88,35,1,4538
1,2,Harmanpreet Kaur,202,181,30.33,-,103,-,-,18,1,4216
2,3,Shafali Verma,111,110,27.89,136.38,81,376,82,18,-,2901
3,4,Jemimah Rodrigues,131,118,29.41,119,76,319,28,16,-,2824
4,5,Mithali Raj,89,84,37.52,97.45,97,240,13,17,-,2364

In [8]:
women_t20i.columns = (
    women_t20i.columns
    .str.replace(" ", "_")
    .str.strip()
)

In [9]:
women_t20i = women_t20i.rename(
    columns = {
        "Rank": "T20I_Rank",
        "Matches": "T20I_Matches",
        "Innings": "T20I_Innings",
        "Average": "T20I_Average",
        "Strike_Rate": "T20I_Strike_Rate",
        "Highest_Score": "T20I_Highest_Score",
        "Fours": "T20I_Fours",
        "Sixes": "T20I_Sixes",
        "Fifties": "T20I_Fifties",
        "Hundreds": "T20I_Hundreds",
        "Runs": "T20I_Runs",
        
})

In [10]:
women_t20i.head(10)

,T20I_Rank,Player,T20I_Matches,T20I_Innings,T20I_Average,T20I_Strike_Rate,T20I_Highest_Score,T20I_Fours,T20I_Sixes,T20I_Fifties,T20I_Hundreds,T20I_Runs
0,1,Smriti Mandhana,171,165,30.25,125.18,112,614,88,35,1,4538
1,2,Harmanpreet Kaur,202,181,30.33,-,103,-,-,18,1,4216
2,3,Shafali Verma,111,110,27.89,136.38,81,376,82,18,-,2901
3,4,Jemimah Rodrigues,131,118,29.41,119,76,319,28,16,-,2824
4,5,Mithali Raj,89,84,37.52,97.45,97,240,13,17,-,2364
5,6,Richa Ghosh,88,74,27.20,144.57,64,154,46,2,-,1333
6,7,Deepti Sharma,149,96,22.67,107.26,64,115,8,2,-,1270
7,8,Veda Krishnamurthy,76,63,18.61,104.55,57,82,11,2,-,875
8,9,Punam Raut,35,31,27.65,92.17,75,81,-,4,-,719
9,10,Jhulan Goswami,68,46,10.94,-,37,-,-,-,-,405

In [11]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Women_T20i"
women_t20i.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Women_T20i' in database 'Indian_Cricket_Analysis'.

In [12]:
women_t20i.to_csv('Cleaned_CSV/Clean_Women_T20i.csv', index = False, encoding = 'utf-8')