In [1]:
import pandas as pd
import numpy as np

In [2]:
# Women Data
women_test = pd.read_csv('../Web_Scraping/Scraped_Data/Women_Test_Analysis.csv')

In [3]:
women_test.shape

(90, 12)

In [4]:
women_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           90 non-null     int64
 1   Player         90 non-null     object
 2   Matches        90 non-null     int64
 3   Innings        90 non-null     int64
 4   Average        90 non-null     float64
 5   Strike Rate    90 non-null     object
 6   Highest Score  90 non-null     int64
 7   Fours          90 non-null     object
 8   Sixes          90 non-null     object
 9   Fifties        90 non-null     object
 10  Hundreds       90 non-null     object
 11  Runs           90 non-null     int64
dtypes: float64(1), int64(5), object(6)
memory usage: 8.6+ KB

In [5]:
women_test.isnull().sum()

Rank             0
Player           0
Matches          0
Innings          0
Average          0
Strike Rate      0
Highest Score    0
Fours            0
Sixes            0
Fifties          0
Hundreds         0
Runs             0
dtype: int64

In [6]:
women_test.dtypes

Rank               int64
Player            object
Matches            int64
Innings            int64
Average          float64
Strike Rate       object
Highest Score      int64
Fours             object
Sixes             object
Fifties           object
Hundreds          object
Runs               int64
dtype: object

In [7]:
women_test.head()

,Rank,Player,Matches,Innings,Average,Strike Rate,Highest Score,Fours,Sixes,Fifties,Hundreds,Runs
0,1,Sandhya Agarwal,13,23,50.45,0,190,0,0,4,4,1110
1,2,Shanta Rangaswamy,16,26,32.60,-,108,-,-,6,1,750
2,3,Shubhangi Kulkarni,19,32,23.33,-,118,-,-,2,1,700
3,4,Mithali Raj,12,19,43.68,39.90,214,86,-,4,1,699
4,5,Smriti Mandhana,8,14,48.84,63.37,149,108,3,3,2,635

In [8]:
women_test.columns = (
    women_test.columns
    .str.replace(" ", "_")
    .str.strip()
)

In [9]:
women_test = women_test.rename(
    columns = {
        "Rank": "Test_Rank",
        "Matches": "Test_Matches",
        "Innings": "Test_Innings",
        "Average": "Test_Average",
        "Strike_Rate": "Test_Strike_Rate",
        "Highest_Score": "Test_Highest_Score",
        "Fours": "Test_Fours",
        "Sixes": "Test_Sixes",
        "Fifties": "Test_Fifties",
        "Hundreds": "Test_Hundreds",
        "Runs": "Test_Runs",
        
})

In [10]:
women_test.head(10)

,Test_Rank,Player,Test_Matches,Test_Innings,Test_Average,Test_Strike_Rate,Test_Highest_Score,Test_Fours,Test_Sixes,Test_Fifties,Test_Hundreds,Test_Runs
0,1,Sandhya Agarwal,13,23,50.45,0,190,0,0,4,4,1110
1,2,Shanta Rangaswamy,16,26,32.60,-,108,-,-,6,1,750
2,3,Shubhangi Kulkarni,19,32,23.33,-,118,-,-,2,1,700
3,4,Mithali Raj,12,19,43.68,39.90,214,86,-,4,1,699
4,5,Smriti Mandhana,8,14,48.84,63.37,149,108,3,3,2,635
5,6,Gargi Banerji,12,22,27.90,-,75,-,-,6,-,614
6,7,Shafali Verma,6,12,55.18,74.38,205,82,14,3,1,607
7,8,Sudha Shah,21,38,18.78,-,62,-,-,1,-,601
8,9,Anjum Chopra,12,20,30.44,-,98,-,-,4,-,548
9,10,Hemlata Kala,7,10,50.30,-,110,-,-,3,2,503

In [11]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Women_Test"
women_test.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Women_Test' in database 'Indian_Cricket_Analysis'.

In [12]:
women_test.to_csv('Cleaned_CSV/Clean_Women_Test.csv', index = False, encoding = 'utf-8')