In [1]:
import pandas as pd

In [2]:
men_test = pd.read_csv("../Data_Cleaning/Cleaned_CSV/Clean_Men_Test.csv")
men_odi = pd.read_csv("../Data_Cleaning/Cleaned_CSV/Clean_Men_ODI.csv")
men_t20i = pd.read_csv("../Data_Cleaning/Cleaned_CSV/Clean_Men_T20I.csv")

women_test = pd.read_csv("../Data_Cleaning/Cleaned_CSV/Clean_Women_Test.csv")
women_odi = pd.read_csv("../Data_Cleaning/Cleaned_CSV/Clean_Women_ODI.csv")
women_t20i = pd.read_csv("../Data_Cleaning/Cleaned_CSV/Clean_Women_T20I.csv")

In [3]:
men_master = pd.merge(
    men_test,
    men_odi,
    on="Player",
    how="outer"
)

men_master = pd.merge(
    men_master,
    men_t20i,
    on="Player",
    how="outer"
)
men_master["Gender"] = "Male"

In [4]:
women_master = pd.merge(
    women_test,
    women_odi,
    on="Player",
    how="outer"
)

women_master = pd.merge(
    women_master,
    women_t20i,
    on="Player",
    how="outer"
)
women_master["Gender"] = "Female"

In [5]:
player_data = pd.concat(
    [men_master, women_master],
    ignore_index=True
)

In [6]:
col = list(player_data.columns)

col[0], col[1] = col[1], col[0]
player_data = player_data[col]

In [7]:
player_data.head()

,Player,Test_Rank,Test_Matches,Test_Innings,Test_Average,Test_Strike_Rate,Test_Highest_Score,Test_Fours,Test_Sixes,Test_Fifties,...,T20I_Innings,T20I_Average,T20I_Strike_Rate,T20I_Highest_Score,T20I_Fours,T20I_Sixes,T20I_Fifties,T20I_Hundreds,T20I_Runs,Gender
0,Aakash Chopra,83.0,10.0,19.0,23.0,34.60,60,49,-,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male
1,Aashish Kapoor,127.0,4.0,6.0,19.4,53.59,42,8,2,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male
2,Aavishkar Salvi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male
3,Abey Kuruvilla,138.0,10.0,11.0,6.6,40.24,35,-,4,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male
4,Abhimanyu Mithun,119.0,4.0,5.0,24.0,48.19,46,16,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male

In [8]:
from sqlalchemy import create_engine

#step 1: Connect to PostgreSQL
#Replace placeholders with your actual details

username = "postgres"
password = "Taksh20"
host = "localhost"
port = "5432"
database = "Indian_Cricket_Analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2: Load DataFrame into PostgreSQL
table_name = "Player_Data"
player_data.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Player_Data' in database 'Indian_Cricket_Analysis'.

In [9]:
player_data.to_csv('Player_Data/Player_Data.csv', index = False, encoding = 'utf-8')

In [10]:
df = player_data[
    [
        "Player"
    ]
]

In [11]:
df.head()

             Player
0     Aakash Chopra
1    Aashish Kapoor
2   Aavishkar Salvi
3    Abey Kuruvilla
4  Abhimanyu Mithun

In [12]:
df.to_csv('Player_Data/Player_Name_Data.csv', index = False, encoding = 'utf-8')